### ISSUE TITLE
Accumulator in Spawn Chunks causing Crash?

### ISSUE THREAD

**Issue by MistMech** [mrh0/createaddition#636]
**Describe the bug**
I have made a modpack for some friends and we've found an issue where an accumulator at spawn is causing crashes when entering within 32 chunks of it

**To Reproduce**
1) Place an accumulator at spawn (ours was 3x3x3) on a server (couldnt get it to happen in Singleplayer)
2) Get it powered and running, up to a high amount of charge
3) Go ~35 chunks away to unload the accumulator
4) Cross a chunk border back in range
5) Game will freeze and require forcefully closing it

**Additional context**
- Mod version: 1.19.2-1.0.0
- Forge version: 1.19.2-43.2.21
- Create version: 1.19.2-0.5.1.b
There are many more mods in the modpack, but we singled out Crafts & Additions as the issue, so I don't believe that it would matter

**Comment by mrh0** [comment]
Please post a crash log

**Comment by MistMech** [comment]
I do have a crash log, although because I have to forcibly close my Minecraft instance,  I dont know if it will actually have the issue or not.

My friends and I did single it out to some incompatibility between Crafts & Additions and Magnesium/Rubidium Extras. I'm theorizing that it is either the Entity Culling or Chunk Updating performance boost from it, but I dont know enough to be sure. I did test using only Create, Crafts & Additions, Rubidium, and Magnesium/Rubidium Extras to make sure it wasnt anything else.

Hope this helps.

[latest.log](https://github.com/mrh0/createaddition/files/12376186/latest.log)

**Comment by MistMech** [comment]
It doesnt seem to actually be a spawn chunk issue though, it can happen anywhere, and also doesnt seem limited to just accumulators. My friends have had it also crash from the electric motor and alternator I believe.

**Comment by tomm2000** [comment]
i'm having the same problem, seems indeed a problem with rubidium, here's my crash log

[crash-2023-09-03_00.41.17-client.txt](https://github.com/mrh0/createaddition/files/12504845/crash-2023-09-03_00.41.17-client.txt)

edit:
after more careful testing the issue seems specific to multiblock accumulators being attached to a connector (no issue arises otherwise):

- 1st time loading the chunk: they are fine, no issue
> i teleport away and teleport back in
- 2nd time loading the chunk they are messed up (see image)
> i teleport away and teleport back in
- 3rd time loading the chunk the game freezes and crashes


![accumulator](https://github.com/mrh0/createaddition/assets/38072918/838d4fc9-e089-45f4-bf39-4739a8be1826)

edit 2:
the issue it's not specific for connectors, it happens with other power transfer methods too, for example a thermal exp. redstone flux cell

**Comment by mrh0** [comment]
Hmm, not sure there is anything i can do, cant see from the logs what i could do to fix this, its all sodium/rubium stuff

**Comment by lottuce-yami** [comment]
It happens without Sodium/Rubidium too. Please see this video demonstration: https://youtu.be/iWg1I6ekwTI
Sometimes accumulator just messes up or makes the chunks disappear, like this:
![2023-09-11 15-10-42 flv_snapshot_00 47 097](https://github.com/mrh0/createaddition/assets/83117017/3b54e290-53dd-434f-823f-7d12cfd36c09)
![2023-09-11 15-08-19 flv_snapshot_01 00 289](https://github.com/mrh0/createaddition/assets/83117017/abccb61c-dbb8-4629-96e4-9d5e2d86b881)
On the memory snapshot at the time of freeze there are ~600MB of `com.mrh0.createaddition.blocks.modular_accumulator.ModularAccumulatorBlockEntity`
![screenshot](https://github.com/mrh0/createaddition/assets/83117017/4f07083b-9250-40f5-8b20-1a2e67346add)
CSV file of the snapshot:
[createaddition.csv](https://github.com/mrh0/createaddition/files/12577000/createaddition.csv)
After closing Minecraft it produces error code -805306369

When I encountered this issue first time I tried to do some memory profiling with Spark:
`[09:28:40] [spark-worker-pool-1-thread-1/INFO] [minecraft/ChatComponent]: [System] [CHAT] [?] Young Gen GC lasting 198 ms. (cause = G1 Evacuation Pause)\n  298.0 MB moved to G1 Old Gen\n    2.4 GB ? 2.7 GB\n  672.0 MB freed from G1 Eden Space\n    672.0 MB ? 0 bytes (100%)`
Not sure if this contains some useful info (gc phases?) or just indicates memory issues, same as the snapshot above.

**Comment by mrh0** [comment]
I'm able to recreate this, It is similar to another bug I had with the connectors but i don't remember how that was fixed

**Comment by mrh0** [comment]
nvm i think this is actually the same bug i though was solved, and i think the visual glitch with the accumulator is a symptom rather than a cause

**Comment by mrh0** [comment]
alright, figured it out, it was indeed the connectors that was the issue, if a connector was present in the same chunk as an accumulator this would happen, will be fixed in the next patch

**Comment by mrh0** [comment]
fix is out

**Comment by tomm2000** [comment]
hey, i'm sorry to bother here again, but was this fixed for 1.18.2 (i had the issue on that version) ? I saw there has been an update for 1.19 and 1.20 but not 1.18 since then

**Comment by plushbean** [comment]
it definitely was not fixed for 1.18 because i just spent several hours debugging only to discover it was large connectors causing client cache errors

**Comment by Atopona** [comment]
NeoForge 1.21.1, same errors
